# Generated by Django 4.0 on 2022-11-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
